.TH "src/image_processor.cpp" 3 "Thu Jul 4 2013" "Version 3.0" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/image_processor.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'image_processor\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLRM\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
