.TH "LRM::Parameter" 3 "Thu Jul 4 2013" "Version 3.0" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRM::Parameter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parameter\&.h>\fP
.PP
Inherited by \fBLRM::ImageProcessorParameter\fP, \fBLRM::MotionProcessorParameter\fP, and \fBLRM::ROSParameter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameter\fP ()"
.br
.ti -1c
.RI "virtual \fB~Parameter\fP ()"
.br
.ti -1c
.RI "virtual int \fBparse\fP (ros::NodeHandle)=0"
.br
.ti -1c
.RI "template<class T > T \fBgetParameterByName\fP (std::string name)"
.br
.ti -1c
.RI "int \fBsetParameterByName\fP (std::string name, boost::any value)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, boost::any > \fBparameter\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLRM::Parameter::Parameter\fP ()\fC [inline]\fP"
.SS "virtual \fBLRM::Parameter::~Parameter\fP ()\fC [inline, virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "template<class T > T \fBLRM::Parameter::getParameterByName\fP (std::stringname)\fC [inline]\fP"
.SS "virtual int \fBLRM::Parameter::parse\fP (ros::NodeHandle)\fC [pure virtual]\fP"
.PP
Implemented in \fBLRM::ROSParameter\fP, \fBLRM::ImageProcessorParameter\fP, and \fBLRM::MotionProcessorParameter\fP\&.
.SS "int \fBLRM::Parameter::setParameterByName\fP (std::stringname, boost::anyvalue)\fC [inline]\fP"
.SH "Member Data Documentation"
.PP 
.SS "std::map<std::string, boost::any> \fBLRM::Parameter::parameter\fP\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
