.TH "LRM::Motion" 3 "Wed Sep 26 2012" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRM::Motion \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <motion\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMotion\fP ()"
.br
.ti -1c
.RI "virtual \fB~Motion\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLRM::Motion::Motion\fP ()"
.SS "\fBLRM::Motion::~Motion\fP ()\fC [virtual]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
