.TH "src/feature_test.cpp" 3 "Wed Sep 26 2012" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/feature_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <image_transport/image_transport\&.h>\fP
.br
\fC#include <sensor_msgs/Image\&.h>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <cv_bridge/cv_bridge\&.h>\fP
.br
\fC#include 'feature\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBImageCb\fP (const sensor_msgs::ImageConstPtr &msg)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "image_transport::Subscriber \fBsub\fP"
.br
.ti -1c
.RI "image_transport::Publisher \fBpub\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBImageCb\fP (const sensor_msgs::ImageConstPtr &msg)"Parameters for Shi-Tomasi algorithm
.PP
Apply corner detection
.PP
Draw corners detected 
.SS "int \fBmain\fP (intargc, char **argv)"\fBmain()\fP 
.SH "Variable Documentation"
.PP 
.SS "image_transport::Publisher \fBpub\fP"
.SS "image_transport::Subscriber \fBsub\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
