.TH "LRM::ROSParameter" 3 "Wed Jul 3 2013" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRM::ROSParameter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mono_odometer\&.h>\fP
.PP
Inherits \fBLRM::Parameter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBROSParameter\fP ()"
.br
.ti -1c
.RI "\fB~ROSParameter\fP ()"
.br
.ti -1c
.RI "int \fBparse\fP (ros::NodeHandle nh)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLRM::ROSParameter::ROSParameter\fP ()\fC [inline]\fP"
.SS "\fBLRM::ROSParameter::~ROSParameter\fP ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "int \fBLRM::ROSParameter::parse\fP (ros::NodeHandlenh)\fC [virtual]\fP"ROS \fBParameter\fP Class 
.PP
Implements \fBLRM::Parameter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
