.TH "LRM::Feature" 3 "Wed Sep 26 2012" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRM::Feature \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <feature\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFeature\fP ()"
.br
.ti -1c
.RI "virtual \fB~Feature\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLRM::Feature::Feature\fP ()"
.SS "\fBLRM::Feature::~Feature\fP ()\fC [virtual]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
