.TH "Tracker" 3 "Mon Nov 25 2013" "Version 1.1" "MGBO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tracker \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ESM\&.h>\fP
.PP
Inherited by \fBESM\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTracker\fP ()"
.br
.ti -1c
.RI "virtual \fB~Tracker\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBTracker::Tracker\fP ()\fC [inline, protected]\fP"
.SS "virtual \fBTracker::~Tracker\fP ()\fC [inline, protected, virtual]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MGBO from the source code\&.
