.TH "LRM" 3 "Wed Sep 26 2012" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRM \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFeature\fP"
.br
.ti -1c
.RI "class \fBDescriptor\fP"
.br
.ti -1c
.RI "class \fBFrame\fP"
.br
.ti -1c
.RI "class \fBMonoOdometer\fP"
.br
.ti -1c
.RI "class \fBMotion\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef cv::Point2f \fBFeature\fP"
.br
.ti -1c
.RI "typedef cv::Rect \fBDescriptor\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBfeature_t\fP { \fBSHI_TOMASI\fP, \fBHARRIS\fP }"
.br
.RI "\fITypes of possible features\&. \fP"
.ti -1c
.RI "enum \fBdescriptor_t\fP { \fBSSD\fP }"
.br
.RI "\fITypes of possible descriptors\&. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef cv::Rect \fBLRM::Descriptor\fP"
.SS "typedef cv::Point2f \fBLRM::Feature\fP"
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLRM::descriptor_t\fP"
.PP
Types of possible descriptors\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISSD \fP\fP

.SS "enum \fBLRM::feature_t\fP"
.PP
Types of possible features\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISHI_TOMASI \fP\fP
.TP
\fB\fIHARRIS \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
