.TH "include/ESM.h" 3 "Mon Nov 25 2013" "Version 1.1" "MGBO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ESM.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br
\fC#include <math_tools\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTracker\fP"
.br
.ti -1c
.RI "class \fBESM\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MGBO from the source code\&.
