.TH "todo" 3 "Mon Nov 25 2013" "Version 1.1" "MGBO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBMember \fBESM::updateSSDSE2Motion\fP (cv::Mat TIRef, cv::Mat ICur, float width, float height, cv::Mat K, cv::Mat norVec, cv::Mat G0, cv::Mat &T, float &RMS)\fP" 1c
Constants K and K^-1 
.PP
What happens with the points out of the mask?  
.IP "\fBMember \fBESM::updateSSDSE3Motion\fP (cv::Mat TIRef, cv::Mat ICur, float width, float height, cv::Mat K, cv::Mat norVec, cv::Mat G0, cv::Mat &T, float &RMS)\fP" 1c
Constants K and K^-1 
.PP

