.TH "boost::numeric::ublas" 3 "Mon Nov 25 2013" "Version 1.1" "MGBO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boost::numeric::ublas \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename MATRIX > MATRIX \fBexpm_pad\fP (const MATRIX &H, typename type_traits< typename MATRIX::value_type >::real_type t=1\&.0, const int p=6)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename MATRIX > MATRIX \fBboost::numeric::ublas::expm_pad\fP (const MATRIX &H, typename type_traits< typename MATRIX::value_type >::real_typet = \fC1\&.0\fP, const intp = \fC6\fP)"
.SH "Author"
.PP 
Generated automatically by Doxygen for MGBO from the source code\&.
