.TH "src/motion.cpp" 3 "Wed Sep 26 2012" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/motion.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'motion\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLRM\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
