.TH "LRM::MonoOdometer" 3 "Wed Sep 26 2012" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRM::MonoOdometer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mono_odometer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMonoOdometer\fP (ros::NodeHandle nh)"
.br
.ti -1c
.RI "virtual \fB~MonoOdometer\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLRM::MonoOdometer::MonoOdometer\fP (ros::NodeHandlenh)"\fBMonoOdometer\fP Constructor: The constructor of the Mono Odometer class\&. Captures and process a new frame and estimates the momentaneous motion\&.
.PP
\fBParameters:\fP
.RS 4
\fInh\fP Node handle of the node of the monocular odometer\&. 
.RE
.PP

.SS "\fBLRM::MonoOdometer::~MonoOdometer\fP ()\fC [virtual]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
