.TH "include/frame.h" 3 "Wed Sep 26 2012" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/frame.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLRM::Frame\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLRM\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef cv::Point2f \fBLRM::Feature\fP"
.br
.ti -1c
.RI "typedef cv::Rect \fBLRM::Descriptor\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLRM::feature_t\fP { \fBLRM::SHI_TOMASI\fP, \fBLRM::HARRIS\fP }"
.br
.RI "\fITypes of possible features\&. \fP"
.ti -1c
.RI "enum \fBLRM::descriptor_t\fP { \fBLRM::SSD\fP }"
.br
.RI "\fITypes of possible descriptors\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
