.TH "LRM" 3 "Wed Jul 3 2013" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRM \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFeature\fP"
.br
.ti -1c
.RI "class \fBImageProcessorParameter\fP"
.br
.ti -1c
.RI "class \fBImageProcessor\fP"
.br
.ti -1c
.RI "class \fBROSParameter\fP"
.br
.ti -1c
.RI "class \fBMonoOdometer\fP"
.br
.ti -1c
.RI "class \fBMotionProcessorParameter\fP"
.br
.ti -1c
.RI "class \fBMotionProcessor\fP"
.br
.ti -1c
.RI "class \fBParameter\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBfeature_t\fP { \fBSHI_TOMASI\fP, \fBHARRIS\fP, \fBORB\fP, \fBFAST\fP, \fBSURF\fP, \fBSIFT\fP, \fBNO_FEATURE\fP }"
.br
.RI "\fITypes of possible features\&. \fP"
.ti -1c
.RI "enum \fBdescriptor_t\fP { \fBSSD\fP }"
.br
.RI "\fITypes of possible descriptors\&. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLRM::descriptor_t\fP"
.PP
Types of possible descriptors\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISSD \fP\fP

.SS "enum \fBLRM::feature_t\fP"
.PP
Types of possible features\&. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISHI_TOMASI \fP\fP
.TP
\fB\fIHARRIS \fP\fP
.TP
\fB\fIORB \fP\fP
.TP
\fB\fIFAST \fP\fP
.TP
\fB\fISURF \fP\fP
.TP
\fB\fISIFT \fP\fP
.TP
\fB\fINO_FEATURE \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
