.TH "include/image_processor.h" 3 "Wed Jul 3 2013" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/image_processor.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'core\&.h'\fP
.br
\fC#include 'parameter\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLRM::ImageProcessorParameter\fP"
.br
.ti -1c
.RI "class \fBLRM::ImageProcessor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLRM\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_RADIUS\fP   10\&.0"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBDEFAULT_RADIUS\fP   10\&.0"
.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
