.TH "include/motion.h" 3 "Wed Sep 26 2012" "Version 0.01" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/motion.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLRM::Motion\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLRM\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
