.TH "LRM::MotionProcessorParameter" 3 "Thu Jul 4 2013" "Version 3.0" "Mono Odometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRM::MotionProcessorParameter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <motion_processor\&.h>\fP
.PP
Inherits \fBLRM::Parameter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMotionProcessorParameter\fP ()"
.br
.ti -1c
.RI "\fB~MotionProcessorParameter\fP ()"
.br
.ti -1c
.RI "int \fBparse\fP (ros::NodeHandle nh)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Motion Processor \fBParameter\fP Class 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBLRM::MotionProcessorParameter::MotionProcessorParameter\fP ()\fC [inline]\fP"
.SS "\fBLRM::MotionProcessorParameter::~MotionProcessorParameter\fP ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "int \fBLRM::MotionProcessorParameter::parse\fP (ros::NodeHandlenh)\fC [virtual]\fP"Motion Processor \fBParameter\fP Class 
.PP
Implements \fBLRM::Parameter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Mono Odometer from the source code\&.
